version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  push-service:
    build: .
    container_name: notification-push-service
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/  # Internal port remains 5672
      REDIS_URL: redis://redis:6379/0  # Internal port remains 6379
